server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectnl_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: projectnl_user
    password: 1234

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  config-location: classpath:mybatis-config.xml
